name: labels

on:
  push:
    branches:
      - main
    paths:
      - ../labels.yml

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: ../labels.yml
