initFields:
    author: Keith Boice <69816300+keithboice@users.noreply.github.com>
    homepage: "https://github.com/keithboice/kb"
    license: MIT
    private: false

initScope: kb

nodeLinker: pnp

plugins:
#    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#      spec: "@yarnpkg/plugin-version"
#    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#      spec: "@yarnpkg/plugin-workspace-tools"
   # - packages/clean/lib/cli.js

yarnPath: .yarn/releases/yarn-2.4.0.cjs
