initFields:
    author: Keith Boice <69816300+keithboice@users.noreply.github.com>
    bin:
        cmd: bin/cli.js
    bugs:
        url: https://github.com/keithboice/kb/issues
    config:
        commitizen:
            path: cz-conventional-changelog
    engines:
        node: ">=14.0.0"
    homepage: https://github.com/keithboice/kb
    languageName: node
    license: MIT
    main: dist/index.js
    private: false
    publishConfig:
        access: public
    repository:
        type: git
        url: https://github.com/keithboice/kb.git
    scripts:
        build: concurrently 'npm:build_cli' 'npm:build_main'
        build_cli:
            ncc build ./bin/cli.js --license ../../LICENSE --stats-out ../../docs/reports/builds/config-jest/vercel.json
            -sm -o dist/cli
        build_coverage: jest --coverage --no-cache
        build_dev: jest --watch
        build_main:
            ncc build src/index.js --license ../../LICENSE --stats-out ../../docs/reports/builds/config-jest/vercel.json
            -sm -o dist/main
        test: jest ../../tests/config-jest.test.js
    version: 0.0.0
initScope: kb
nodeLinker: pnp
plugins: "[{path=.yarn/plugins/@yarnpkg/plugin-stage.cjs spec=@yarnpkg/plugin-stage}
    {path=.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs spec=@yarnpkg/plugin-workspace-tools}
    {path=.yarn/plugins/@yarnpkg/plugin-version.cjs spec=@yarnpkg/plugin-version}]"
yarnPath: .yarn/releases/yarn-2.4.0.cjs
