initFields:
    author: Keith Boice <69816300+keithboice@users.noreply.github.com>
    bin:
        bin: ./bin.js
    files: ./**/*
    homepage: "https://github.com/keithboice/kb"
    installConfig:
        hoistingLimits: none
    languageName: node
    license: MIT
    main: ./index.js
    module: ./index.mjs
    private: false
    publishConfig:
        access: public
        bin: ./bin.js
    types: commonjs
    script:
        purge: "rm README.md && yarn init && rm -rf node_modules"

initScope: kb

nodeLinker: pnp

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
      spec: "@yarnpkg/plugin-stage"
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs