initFields:
    author: Keith Boice <69816300+keithboice@users.noreply.github.com>
    bugs:
        url: "https://github.com/keithboice/kb/issues"
    files: index.js
    homepage: "https://github.com/keithboice/kb"
    installConfig:
        hoistingLimits: none
    languageName: node
    license: MIT
    main: index.js
    private: false
    publishConfig:
        access: public
    repository:
        type: git
        url: "https://github.com/keithboice/kb.git"
    script:
        purge: rm README.md && yarn init && rm -rf node_modules
    types: commonjs

initScope: kb

nodeLinker: pnp

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
      spec: "@yarnpkg/plugin-stage"
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: "@yarnpkg/plugin-workspace-tools"
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
