name: automerge
on:
    pull_request:
        types:
            - labeled
            - unlabeled
            - synchronize
            - edited
            - ready_for_review
            - reopened
            - unlocked
    pull_request_review:
        types:
            - submitted
    check_suite:
        types:
            - completed
jobs:
    automerge:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            MERGE_COMMIT_MESSAGE: "pull-request-description"
            UPDATE_LABELS: "state:done"
            MERGE_DELETE_BRANCH: true
        steps:
            - name: automerge
              uses: "pascalgn/automerge-action@v0.13.0"
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
