blank_issues_enabled: false
contact_links:
    -   name:      fix
        url:       https://github.com/keithboice/kb/issues/new?template=fix.md&assignees=keithboice&labels=branch%3Afix&title=words
        about:     A bug or defect
#        title:     "title"
#        labels:    "branch:fix","tag:fix"
#        assignees: "keithboice"
    
    -   name:      feature
        url:       https://github.com/keithboice/kb/issues/new?template=feature.md&assignees=keithboice&labels=branch%3Afeat&title=words
        about:     A new feature or enhancement
#        title:     "title"
#        labels:    "tag:feat","branch:feat"
#        assignees: "keithboice"
    
    -   name:      chore
        url:       https://github.com/keithboice/kb/issues/new?template=chore.md&assignees=keithboice&labels=branch%3Achore&title=words
        about:     A non-functional requirement on technical task
#        title:     "title"
#        labels:    "tag:chore","branch:chore"
#        assignees: "keithboice"
    
    -   name:      action
        url:       https://github.com/keithboice/kb/issues/new?template=action.md&assignees=keithboice&labels=branch%3Abot&title=words
        about:     A github action or automated task
#        title:     "trigger the <action> action"
#        labels:    "tag:action","branch:bot","tag:automated"
#        assignees: "bot"
