blank_issues_enabled: false
contact_links:
    - name: fix
      url: https://github.com/keithboice/kb/issues/new?template=fix.md&assignees=keithboice&labels=branch%3Afix&title=fixes
      about: A bug or defect
      title: "fixes"
      labels: branch:fix,tag:fix
      assignees: "keithboice"

    - name: feature
      url: https://github.com/keithboice/kb/issues/new?template=feature.md&assignees=keithboice&labels=branch%3Afeat&title=feature
      about: A new feature or enhancement
      title: "feature"
      labels: tag:feat,branch:feat
      assignees: "keithboice"

    - name: chore
      url: https://github.com/keithboice/kb/issues/new?template=chore.md&assignees=keithboice&labels=branch%3Achore&title=chore
      about: A non-functional requirement on technical task
      title: "chore"
      labels: tag:chore,branch:chore
      assignees: "keithboice"

    - name: action
      #url: https://github.com/keithboice/kb/issues/new?template=action.md&assignees=keithboice&labels=branch%3Abot&title=trigger
      about: A github action or automated task
      title: "trigger"
      labels: tag:action,branch:bot,tag:automated
      assignees: "bot"
