name: branch

on:
    issues:
        types: [opened]

    workflow_dispatch:

jobs:
    branch:
        runs-on: ubuntu-latest

        steps:
          - name: Create Issue Branch
            uses: robvanderleek/create-issue-branch@v1.4
