name: code

on:
  #push

  workflow_dispatch:

jobs:
  code:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        language: ['javascript']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1
