name: branch

on:
    issues:
        types:
          - opened
          - edited
    workflow_dispatch:

jobs:
    branch:
        runs-on: ubuntu-latest

        steps:
            - name: Create Branch
              uses: robvanderleek/create-issue-branch@master
              env:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
