name: ci

on:
  [push, pull_request]

jobs:
    ci:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [15.x]
                language: ['javascript']

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Nodejs ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build
              run: |
                  npm install
