name: lint

on: [pull_request,push,workflow_dispatch]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm install yarn
            #- run: npm install
            #- run: npm install @kb/clean
            #- uses: wagoid/commitlint-github-action@v1
