blank_issues_enabled: true
contact_links:
    - name: fix
      url: https://github.com/keithboice/.github/blob/main/ISSUE_TEMPLATE/bug.md
      about: a bug or defect.
      title: "[BUG] title"
      labels: bug
      assignees: ""

    - name: feature
      url: https://github.com/keithboice/.github/blob/main/ISSUE_TEMPLATE/feature.md
      about: a new feature
      title: "[FTR] title"
      labels: feat
      assignees: ""

    - name: tech
      url: https://github.com/keithboice/.github/blob/main/ISSUE_TEMPLATE/tech.md
      about: stories that are purely technical in nature
      title: "[TECH] title"
      labels: tech
      assignees: ""

    - name: docs
      url: https://github.com/keithboice/.github/blob/main/ISSUE_TEMPLATE/docs.md
      about: Documentation only changes
      title: "[DOC] trigger the <action> action"
      labels: docs
      assignees: ""

    - name: action
      url: https://github.com/keithboice/.github/blob/main/ISSUE_TEMPLATE/action.md
      about: will trigger a github action on the repo
      title: "[TST] trigger the <action> action"
      labels: action, rel:bot, tag:automated
      assignees: ""

    - name: all-in-yml test
      about: testing to see if title and labels can live in config.yml
      title: "[TST] trigger the <action> action"
      labels: action, rel:bot, tag:automated
      assignees: ""
